var SomaFunc = require('../aula002/funcoes/soma')
var Subfunc = require('../aula002/funcoes/subtracao')
let Multifunc = require('../aula002/funcoes/multiplica')
console.log(SomaFunc(6, 4))
console.log(Subfunc(5, 3))
console.log(Multifunc(10, 20))